base.url=http://20.75.201.176/
app.username=careconnect
app.password=Admin@123
browser=chrome
explicit.wait.seconds=15
implicit.wait.seconds=0
page.load.timeout.seconds=30
app.slowmo.ms=1500
report.path=reports/
screenshot.path=screenshots/
